server:
  port: 8080

spring:
  mail:
    host: smtp.example.com  # 替换为您的SMTP服务器地址，例如 smtp.qq.com
    port: 587              # SMTP端口，通常是587或465
    username: your-email@example.com # 您的邮箱账号
    password: your-password # 您的邮箱密码或授权码
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jobspark?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
    username: root
    password: your-password
  redis:
    host: localhost
    port: 6379
    # password: your_password
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
        max-wait: -1ms

# MyBatis-Plus configuration
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0


jwt:
  # token密钥生成在线地址：https://www.btool.cn/token-generator?symbols=true
  secret: Z!{Q'I#FU|+PlA#CG0Rd0yDZBU@QU-L\RMqpPF-smXxp}7,o:OHzhTd[![oqf-"f # 至少32位
  access-token-expiration: 7200    # Access Token 有效期：两小时（秒）

langchain4j:
  qdrant:
    collection-name: jobspark_resume
    host: localhost
    port: 6334
    use-tls: false
    payload-text-key: content
    vector-size: 1024 # text-embedding-v3/v4 默认维度
    # api-key: your-api-key # 如果需要鉴权请配置

# 生成接口文档
springdoc:
  api-docs:
    path: /swagger/api-docs
  swagger-ui:
    path: /swagger/swagger-ui
    operations-sorter: method
    tags-sorter: alpha
  info:
    title: My Spring Boot API
    version: 1.0.0
    description: 这是一个示例 API 文档